import os, json, time, math, subprocess, urllib.request, re, random
from pathlib import Path

MAX_HOURS = 72
WORK_DIR = "/global/u1/v/vinny/projects/topreco-agent"
PIPELINE_DIR = "/global/u1/v/vinny/projects/topreconstruction"
CODE_PATH = f"{PIPELINE_DIR}/top_reco/src/triplet_ml/select_triplets.py"
LAB_PATH = f"{WORK_DIR}/labbook.md"
CHAMP_PATH = f"{WORK_DIR}/champion_state.json"
REPORT_PATH = f"{WORK_DIR}/marathon_session_report.md"
HISTORY_PATH = f"{WORK_DIR}/champion_history.md"
API_KEY = os.environ.get("OPENAI_API_KEY")
BASE_URL = "https://api.cborg.lbl.gov/v1/chat/completions"
MODEL = "lbl/gpt-oss-120b"

def log(msg):
    ts = time.strftime("%Y-%m-%d %H:%M:%S")
    with open("hybrid_discovery_v1.log", "a") as f: f.write(f"[{ts}] {msg}\n")
    print(f"[{ts}] {msg}")

def call_model(msgs):
    data = json.dumps({"model": MODEL, "messages": msgs, "temperature": 0.7}).encode("utf-8")
    req = urllib.request.Request(BASE_URL, data=data, headers={"Content-Type": "application/json", "Authorization": f"Bearer {API_KEY}"})
    try:
        with urllib.request.urlopen(req, timeout=300) as resp: return json.loads(resp.read().decode())["choices"][0]["message"]["content"]
    except Exception as e:
        log(f"API Error: {e}")
        return None

def sanitize_logic(raw_logic):
    # 1. Handle common characters and formatting
    clean = raw_logic.replace('\\n', '\n').replace('\u2011', '-').replace('\u2013', '-').replace('\u202F', ' ')
    
    # 2. Auto-fix math namespace (exp -> math.exp, etc)
    math_funcs = ['exp', 'sqrt', 'tanh', 'log', 'sin', 'cos', 'pi', 'pow']
    for func in math_funcs:
        # Regex to find func( but not math.func(
        clean = re.sub(r'(?<!math\.)\b' + func + r'\b', 'math.' + func, clean)

    lines = []
    for l in clean.split('\n'):
        l = l.strip()
        if not l or l.startswith('#') or 'print(' in l: continue
        # Ignore lines that are just sentences
        if '=' not in l and '(' not in l and 'math.' not in l: continue
        lines.append("            " + l)
    return "\n".join(lines)

def extract_json(text):
    stack = []
    start_idx = -1
    for i, char in enumerate(text):
        if char == '{':
            if not stack: start_idx = i
            stack.append(char)
        elif char == '}':
            if stack:
                stack.pop()
                if not stack:
                    candidate = text[start_idx:i+1]
                    try: return json.loads(candidate)
                    except: continue
    return None

def generate_thorough_report():
    try:
        with open(CHAMP_PATH, "r") as f: champ = json.load(f)
        
        # Read the labbook to get the last few successes
        history_snippet = ""
        if os.path.exists(LAB_PATH):
            with open(LAB_PATH, "r") as f:
                history_snippet = "\n".join(f.readlines()[-20:])

        report = f"""# Top Reconstruction Marathon — Deep Session Report
**Updated:** {time.strftime("%Y-%m-%d %H:%M:%S")}
**Current Best Efficiency:** {champ['efficiency']:.4f}
**Champion Strategy Slug:** {champ['slug']}

## 1. Champion Physics Rationale
{champ.get('motivation', 'No detailed motivation provided.')}

## 2. Champion Implementation Logic
The following code block represents the current state-of-the-art for this session. It combines fixed mass priors with the evolved correction factors.

```python
{champ.get('logic', 'No logic available.')}
```

## 3. Latest Evolution Path
```text
{history_snippet}
```

---
*Report generated by Marathon Harness v14.5*
"""
        with open(REPORT_PATH, "w") as f: f.write(report)
        
        # Append to a permanent history file
        with open(HISTORY_PATH, "a") as f:
            f.write(f"\n--- New Champion: {champ['efficiency']:.4f} ({champ['slug']}) ---\n")
            f.write(f"Motivation: {champ.get('motivation')}\n")
            f.write(f"Logic:\n{champ.get('logic')}\n")

    except Exception as e:
        log(f"Report Generation Error: {e}")

def main():
    start_time, iter_idx = time.time(), 95000
    log("=== Top Reconstruction Marathon Harness v14.5 (HARDENED PHYSICS) ===")
    
    while (time.time() - start_time) < (MAX_HOURS * 3600):
        try:
            with open(CHAMP_PATH, "r") as f: champ = json.load(f)
        except: 
            log("State file error."); time.sleep(10); continue

        generate_thorough_report()
        
        mode, is_mut = ("MUTATION", True) if random.random() < 0.20 else ("REFINEMENT", False)
        
        prompt = f"""Physicist: Devise a NOVEL reconstruction strategy. 
Current best: {champ['efficiency']:.4f}.

You are writing the body of a loop over candidates 't'.
Available local variables:
- score (t.score)
- triplet_mass (t.triplet_mass)
- triplet_pt (t.triplet_pt)
- triplet_eta (t.triplet_eta)
- ratio_ab, ratio_ac, ratio_bc
- dr_ab, dr_ac, dr_bc

You MUST define 'combined_score'. 
OUTPUT ONLY JSON: {{'slug': 'strat_v1', 'logic': '...', 'motivation': '...'}}
"""
        log(f"--- ITERATION {iter_idx}: {mode} MODE ---")
        resp = call_model([{"role": "user", "content": prompt}])
        if not resp: 
            iter_idx += 1; time.sleep(10); continue
            
        discovery = extract_json(resp)
        if not discovery:
            log("JSON extraction failed."); iter_idx += 1; continue

        try:
            strat_slug = discovery["slug"].replace(" ", "_").replace("-", "_")
            # Ensure slug is unique per iteration
            strat_slug = f"{strat_slug}_{iter_idx}"
            strat_logic = sanitize_logic(discovery["logic"])
            if "combined_score" not in strat_logic:
                log("combined_score missing."); iter_idx += 1; continue
        except Exception as e:
            log(f"Processing Error: {e}"); iter_idx += 1; continue

        # 1. Reset
        subprocess.run(f"agent_kit/.venv/bin/python3 {WORK_DIR}/reset_and_feature_patch.py", shell=True)
        
        # 2. Inject (Robust Regex)
        with open(CODE_PATH, "r") as f: content = f.read()
        # Find STRATEGIES line regardless of existing content
        content = re.sub(r'STRATEGIES = .*', f'STRATEGIES = ("greedy_disjoint", "top1", "topk", "threshold", "best_pair_avg_disjoint", "{strat_slug}")', content)
        
        impl = f"    if strategy == \"{strat_slug}\":\n"
        impl += "        scored_cands = []\n"
        impl += "        for t in candidates:\n"
        impl += "            import math\n"
        # PRE-BIND VARIABLES FOR ROBUSTNESS
        impl += "            score = t.score; triplet_mass = t.triplet_mass; triplet_pt = t.triplet_pt; triplet_eta = t.triplet_eta\n"
        impl += "            ratio_ab = t.ratio_ab; ratio_ac = t.ratio_ac; ratio_bc = t.ratio_bc\n"
        impl += "            dr_ab = t.dr_ab; dr_ac = t.dr_ac; dr_bc = t.dr_bc\n"
        # Standard priors
        impl += "            best_w = min([t.mij_ab, t.mij_ac, t.mij_bc], key=lambda m: abs(m - 80.4))\n"
        impl += "            top_prior = math.exp(-0.5 * ((t.triplet_mass - 162.0) / (18.0 if t.triplet_mass >= 162.0 else 25.0))**2)\n"
        impl += "            w_prior = math.exp(-0.5 * ((best_w - 80.4) / 18.0)**2)\n"
        impl += "            base_score = max(t.score, 1e-6) * top_prior * w_prior\n"
        # Model Logic
        impl += strat_logic + "\n"
        impl += "            new_cand = TripletCandidate(i=t.i, j=t.j, k=t.k, score=combined_score, is_truth=t.is_truth, triplet_pt=t.triplet_pt, triplet_eta=t.triplet_eta, triplet_phi=t.triplet_phi, triplet_mass=t.triplet_mass, mij_ab=t.mij_ab, mij_ac=t.mij_ac, mij_bc=t.mij_bc, dr_ab=t.dr_ab, dr_ac=t.dr_ac, dr_bc=t.dr_bc, ratio_ab=t.ratio_ab, ratio_ac=t.ratio_ac, ratio_bc=t.ratio_bc)\n"
        impl += "            scored_cands.append(new_cand)\n"
        impl += "        scored_cands.sort(key=lambda x: (-x.score, x.i, x.j, x.k))\n"
        impl += "        return _solve_exact_disjoint(scored_cands, max_top=max_top_per_event)\n"

        content = content.replace('    if strategy == "greedy_disjoint":', impl + '\n    if strategy == "greedy_disjoint":')
        with open(CODE_PATH, "w") as f: f.write(content)
        
        # 3. Eval
        if subprocess.run(f"agent_kit/.venv/bin/python3 -m py_compile {CODE_PATH}", shell=True).returncode == 0:
            eval_cmd = f"PYTHONPATH={PIPELINE_DIR}/top_reco/src /global/homes/v/vinny/.conda/envs/topml/bin/python -m triplet_ml select_triplets --inference {PIPELINE_DIR}/artifacts/run_prof/infer_eval/inference_test_xgb.parquet --strategy {strat_slug} --output-dir artifacts/iter{iter_idx}_eval --min-score 0.0 --max-top-per-event 4 --no-progress"
            subprocess.run(eval_cmd, shell=True)
            res = subprocess.run(f"agent_kit/.venv/bin/python3 {WORK_DIR}/real_eval.py artifacts/iter{iter_idx}_eval/selected_triplets.parquet 0 2000", shell=True, capture_output=True, text=True)
            if res.stdout and "Efficiency: " in res.stdout:
                p = float(res.stdout.split("Efficiency: ")[1].split("\n")[0].strip())
                log(f"Result: {p:.4f}")
                if p > champ["efficiency"]:
                    log(f"*** NEW CHAMPION! {p:.4f} > {champ['efficiency']:.4f} ***")
                    champ["efficiency"] = p; champ["slug"] = strat_slug; champ["logic"] = strat_logic; champ["motivation"] = discovery.get("motivation")
                    with open(CHAMP_PATH, "w") as f: json.dump(champ, f, indent=2)
                    generate_thorough_report()
                with open(LAB_PATH, "a") as f: 
                    f.write(f"\n#### Iteration {iter_idx}: {strat_slug}\n- Efficiency: {p:.4f}\n- Mode: {mode}\n- Motivation: {discovery.get('motivation')}\n")
            else: log(f"Eval failed for iter {iter_idx}")
        else: log(f"Syntax error for iter {iter_idx}")
            
        iter_idx += 1; time.sleep(1)

if __name__ == "__main__": main()
